#!/bin/sh

if [ "$1" = "" ] ; then
 echo 'make_VMCondor_user_data PREFIX'
 exit 1
fi

cat VMCondor_cloud-config	 > tmp_cloud-config
cat $1.write_files		>> tmp_cloud-config
cat VMCondor_condor		>> tmp_cloud-config
sed 's/^/  /' $1.condor		>> tmp_cloud-config

./make_multipart_user_data            \
   VMCondor_comments:comment          \
   tmp_cloud-config:cloud-config      \
   VMCondor_ucernvm:ucernvm           \
   VMCondor_shellscript:x-shellscript \
   > $1.user_data
